name = "finance-tracker"
compatibility_date = "2025-07-18"

[[kv_namespaces]]
binding = "FINANCE_KV"
id = "c49ad8b111f94163bee7ae0bca58c9a0"

[[r2_buckets]]
binding = "FINANCE_R2"
bucket_name = "finance-tracker-docs"

[build]
command = "cd frontend && npm run build"
watch_dir = ["frontend/src", "functions"]
